### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by Comandorr** [StrangRoll/Good-company#1]
как играть?

**Comment by Comandorr** [comment]
сам пошел нахуй

**Comment by StrangRoll** [comment]
Как же ты заебал, пидорасина, иди на хуй со своими играми. Это гит нахуй, здесь блядь не играют

**Comment by StrangRoll** [comment]
Пиздюк малолетний

**Comment by Comandorr** [comment]
я тебя старше

**Comment by Comandorr** [comment]
я тебя старше
